# Generated by Django 4.0.2 on 2022-07-12 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Название автомобиля')),
                ('manufacturer_charge', models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='Наценка производителя')),
            ],
        ),
    ]
