# Generated by Django 4.0.2 on 2022-07-12 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detail_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=100, verbose_name='Тип детали')),
            ],
        ),
        migrations.AlterField(
            model_name='car',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название автомобиля'),
        ),
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Стоимость детали')),
                ('quantity', models.PositiveSmallIntegerField(default=1, verbose_name='Количество деталей')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car', to='car.car', verbose_name='Автомобиль')),
                ('detail_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detail', to='car.detail_type', verbose_name='Тип детали')),
            ],
        ),
    ]
