# Generated by Django 4.0.2 on 2022-07-12 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0002_detail_type_alter_car_name_detail'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'verbose_name': 'Автомобиль', 'verbose_name_plural': 'Автомобили'},
        ),
        migrations.AlterModelOptions(
            name='detail',
            options={'verbose_name': 'Деталь', 'verbose_name_plural': 'Детали'},
        ),
        migrations.AlterModelOptions(
            name='detail_type',
            options={'verbose_name': 'Тип детали', 'verbose_name_plural': 'Типы деталей'},
        ),
    ]
