# Generated by Django 4.0.2 on 2022-07-12 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0004_car_price_detail_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='manufacturer_charge',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Наценка производителя'),
        ),
    ]
