# Generated by Django 4.0.2 on 2022-07-12 18:15

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0005_alter_car_manufacturer_charge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='manufacturer_charge',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Наценка производителя'),
        ),
        migrations.AlterField(
            model_name='car',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Общая стоимость'),
        ),
        migrations.AlterField(
            model_name='detail',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='car.car', verbose_name='Автомобиль'),
        ),
        migrations.AlterField(
            model_name='detail',
            name='detail_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='car.detail_type', verbose_name='Тип детали'),
        ),
        migrations.AlterField(
            model_name='detail',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Стоимость детали'),
        ),
        migrations.AlterField(
            model_name='detail',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Общая стоимость'),
        ),
    ]
