# Generated by Django 4.0.2 on 2022-07-12 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0006_alter_car_manufacturer_charge_alter_car_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Extra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, verbose_name='Параметр')),
                ('value', models.CharField(max_length=100, verbose_name='Значение')),
                ('detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extras', to='car.detail', verbose_name='Доп. Параметры')),
            ],
        ),
    ]
