# Generated by Django 4.0.2 on 2022-07-12 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0007_extra'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='extra',
            options={'verbose_name': 'Дополнение', 'verbose_name_plural': 'Дополнения'},
        ),
        migrations.AlterField(
            model_name='extra',
            name='detail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extras', to='car.detail', verbose_name='Деталь'),
        ),
    ]
