# Generated by Django 4.0.2 on 2022-07-12 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0008_alter_extra_options_alter_extra_detail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='extra',
            old_name='key',
            new_name='detail_key',
        ),
        migrations.RenameField(
            model_name='extra',
            old_name='value',
            new_name='detail_value',
        ),
    ]
